sonar.projectKey=task-processor
sonar.projectName=Distributed Task Processor
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=master,worker

# Exclude node_modules from code analysis
sonar.exclusions=**/node_modules/**, master/public/style.css
