sonar.projectKey=task-processor
sonar.projectName=Distributed Task Processor
sonar.projectVersion=2.0

sonar.sources=apps/api/src,apps/web/app
sonar.tests=apps/api/tests
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**
